### ISSUE TITLE
Error compiling apiExample.dproj 

### ISSUE THREAD

**Issue by viniciusmelocodes** [GabrielTrigo/telegram-bot-delphi#1]
Scenario:
main branch
uTelegramAPI class line 196
Delphi 10.1 Berlin
When trying to compile I see these 2 errors below: 
[Error 1]https://ibb.co/KV9RbPw
[Error 2]https://ibb.co/SQHzv1r

**Comment by GabrielTrigo** [comment]
Delphi 10.1 não tem declaração de variáveis InLine, declare elas no escopo local

**Comment by viniciusmelocodes** [comment]
Qual é o tipo do Enum?
